{
 "title": "Outstation Service",
 "tags": [
  "nodejs",
  "outstation"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(nodejs_version_info, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Pub/Sub Messages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Messages Received",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(redis_pubsub_messages_received_total{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Messages Published",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(redis_pubsub_messages_published_total{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Channels",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "sum(redis_pubsub_channels{instance=~\"$instance\"}) by (channel)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outstation Request (Subscriber) Channel Resolve Latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(redis_pubsub_latency_seconds_bucket{instance=~\"$instance\",channel=\"outstationrequest_SUBSCRIBER\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outstation Request (Publisher) Channel Resolve Latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "rate(redis_pubsub_latency_seconds_bucket{instance=~\"$instance\", channel=\"outstationrequest_PUBLISHER\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Device Keypad Interface (Publisher) Channel Resolve Latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "rate(redis_pubsub_latency_seconds_bucket{instance=~\"$instance\", channel=\"device-keypadinterfacemessage_PUBLISHER\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Channel Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate(redis_pubsub_latency_seconds_sum{instance=~\"$instance\"}[5m]))/sum(rate(redis_pubsub_latency_seconds_count{instance=~\"$instance\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Application Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Average Request Duration (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum(rate(http_response_duration_ms_sum{instance=~\"$instance\"}[5m])) by (method, path, status)\n/\nsum(rate(http_response_duration_ms_count{instance=~\"$instance\"}[5m])) by (method, path, status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Durations Across All Paths",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 27 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_bucket{instance=~\"$instance\"}[5m])) by (le, path)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node.js Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(nodejs_version_info{instance=~\"$instance\"}) by (version)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Process Restart Times",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(changes(process_start_time_seconds{instance=~\"$instance\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Active HTTP Requests By Method",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_active_requests{instance=~\"$instance\"}) by (method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Requests By Path",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum(http_requests_path_total{instance=~\"$instance\"}) by (path)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate Of Each Request Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 35 },
   "targets": [
    {
     "expr": "rate(http_requests_path_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Requests Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "sum(http_requests_total{instance=~\"$instance\"}) by (method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Event Loop Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_seconds{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Active Handlers/Requests Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nodejs_active_handles_total{instance=~\"$instance\"}",
     "legendFormat": "Active Handler - {{instance}}"
    },
    {
     "expr": "nodejs_active_requests_total{instance=~\"$instance\"}",
     "legendFormat": "Active Request - {{instance}}"
    }
   ]
  },
  { "title": "Garbage Collector", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Garbage Collector Duration",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(nodejs_gc_duration_seconds_bucket[5m])) by (le, gc_type))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Garbage Collector Operations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 52 },
   "targets": [
    {
     "expr": "sum(nodejs_gc_duration_seconds_count{instance=~\"$instance\"}) by (kind)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Garbage Collector Duration Distributed Across Buckets",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 52 },
   "targets": [
    {
     "expr": "sum(nodejs_gc_duration_seconds_bucket{module=\"fusion\", sub_module=\"outstation-service\"}) by (le, kind)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "CPU and Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Heap Total Detail",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nodejs_heap_space_size_total_bytes{instance=~\"$instance\"}",
     "legendFormat": "Heap Total - {{instance}} - {{space}}"
    }
   ]
  },
  {
   "title": "Heap Used Detail",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nodejs_heap_space_size_used_bytes{instance=~\"$instance\"}",
     "legendFormat": "Heap Used - {{instance}} - {{space}}"
    }
   ]
  },
  {
   "title": "Heap Available Detail",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nodejs_heap_space_size_available_bytes{instance=~\"$instance\"}",
     "legendFormat": "Heap Used - {{instance}} - {{space}}"
    }
   ]
  },
  {
   "title": "Process Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=~\"$instance\"}",
     "legendFormat": "Process Memory - {{instance}}"
    },
    {
     "expr": "nodejs_heap_size_total_bytes{instance=~\"$instance\"}",
     "legendFormat": "Heap Total - {{instance}}"
    },
    {
     "expr": "nodejs_heap_size_used_bytes{instance=~\"$instance\"}",
     "legendFormat": "Heap Used - {{instance}}"
    },
    {
     "expr": "nodejs_external_memory_bytes{instance=~\"$instance\"}",
     "legendFormat": "External Memory - {{instance}}"
    }
   ]
  },
  {
   "title": "Process CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "irate(process_cpu_user_seconds_total{instance=~\"$instance\"}[2m]) * 100",
     "legendFormat": "User CPU - {{instance}}"
    },
    {
     "expr": "irate(process_cpu_system_seconds_total{instance=~\"$instance\"}[2m]) * 100",
     "legendFormat": "Sys CPU - {{instance}}"
    }
   ]
  }
 ]
}